# notion
# Source: https://github.com/makenotion/notion-mcp-server
# Toolathlon Version: https://github.com/lockon-n/notion-mcp-server
# Toolathlon_GYM: ../../local_servers/notion-mcp-server

type: stdio
name: notion
params:
  command: node
  args:
    - "${local_servers_paths}/notion-mcp-server/bin/cli.mjs"
    - "--page-id"
    - ""
  env:
    OPENAPI_MCP_HEADERS: "{\"Authorization\": \"Bearer ntn-placeholder\", \"Notion-Version\": \"2022-06-28\" }"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 100
cache_tools_list: true